# Site settings
title: 'Bri + Jase'
baseurl: ''
distbase: './dist'
imagebase: './dist/images'
wedding_date: 'January 5, 2019'
wedding_location: 'Chicago, Illinois'

source: _src

# Build settings
permalink: pretty
exclude: [
  'node_modules',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  'README.md',
  'SOURCE',
  'assets/'
]
languages: ['en']
